- name: Set up and run metrics analysis on remote Ubuntu server
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Ensure Python and pip are installed
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install required Python packages
      pip:
        name:
          - pandas
        executable: pip3

    - name: Copy the Python analysis script to the remote server
      copy:
        src: ../files/analyze_metrics.py
        dest: /tmp/analyze_metrics.py
        mode: '0755'

    - name: Execute the Python analysis script
      command: python3 /tmp/analyze_metrics.py
      register: result

    - name: Print the result of the Python script
      debug:
        msg: "{{ result.stdout }}"

    - name: Fetch the daily usage stats file back to the local machine
      fetch:
        src: /var/log/daily_usage_stats.csv
        dest: ./files/daily_usage_stats.csv
        flat: yes