- name: Run metrics connection script on Ubuntu server
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Copy metrics script to the server
      ansible.builtin.copy:
        src: ../files/collect_cpu_metrics.sh
        dest: /tmp/collect_cpu_metrics.sh
        mode: '0755'

    - name: Execute the metrics script
      ansible.builtin.shell: /tmp/collect_cpu_metrics.sh

    - name: Add a cron job to run the metrics script every hour
      cron:
        name: "Collect CPU and memory metrics every hour"
        minute: "0"
        hour: "*"
        job: "/tmp/collect_cpu_metrics.sh"
        state: present