apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ include "redis-cluster.name" . }}