apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: {{ .Values.cluster.nodes }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          args:
            - "--cluster-enabled yes"
            - "--cluster-node-timeout 5000"
            - "--appendonly yes"
            - "--save 900 1"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}